#!/usr/bin/env python3
"""Generates microcode.cpp and microtags.cpp from the KD11-B control store
transcription (the .tsv listings in ~/1105rom/derived, transcribed from the
microcode listing pages of the 11/05 engineering drawings).

Both drawing sets are read: the 1973 one is M7261 rev E, the 1976 one rev F.
They differ only in the AUX and CKO bits of 14 microwords; this asserts that,
and keeps AUX for both revisions. CKO is not on any KM11 lamp.

BUT is taken as printed, bit 3 leftmost: IR-DECODE lands on F-5 (KD11-B manual
table 5-4), SSYNC on INT-1 ("SET SLAVE SYNC") and IR-CLK on F-4. Before October
2026 the transcription unscrambled BUT into signal order, which was wrong; it has
been corrected there too.

    python3 gen_microcode.py [path to derived/]
"""
import os
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/1105rom/derived')
HERE = os.path.dirname(os.path.abspath(__file__))


def load(name):
    rows = [l.rstrip('\n').split('\t') for l in open(os.path.join(SRC, name)) if not l.startswith('#')]
    head = rows[0]
    return {int(r[head.index('LOC')], 8): dict(zip(head, r)) for r in rows[1:]}


rev_e = load('kd11b-microcode-1973.tsv')
rev_f = load('kd11b-microcode-1976.tsv')
assert rev_e.keys() == rev_f.keys() and len(rev_e) == 214

SAME = ['NAM', 'NXTADDR', 'ALU', 'CRI', 'SPA', 'SPAMUX', 'BUT']
for loc, e in rev_e.items():
    f = rev_f[loc]
    for k in SAME:
        assert e[k] == f[k], (oct(loc), k)

words = []
for loc in range(256):
    e = rev_e.get(loc)
    if e is None:
        words.append((0, 0, 0, 0, ''))
        continue
    f = rev_f[loc]
    nxt = int(e['NXTADDR'], 8)
    but = int(e['BUT'], 2)
    ctl = but | 0x10 | (0x20 if e['SPAMUX'] == 'ROM' else 0) | (0x40 if e['CRI'] == '1' else 0)
    alu = int(e['ALU'], 2) | (int(e['AUX']) << 5) | (int(f['AUX']) << 6)
    spa = int(e['SPA'])
    assert 0 <= spa < 16
    words.append((nxt, ctl, alu, spa, e['NAM']))

out = ['// KD11-B control store, the fields a KM11 can see, indexed by microaddress.',
       '// Generated by gen_microcode.py from the transcription of the microcode',
       '// listing in the 11/05 engineering drawings; do not edit by hand.',
       '#include "microcode.h"', '',
       'const MicroWord microcode[256] = {']
for loc, (nxt, ctl, alu, spa, name) in enumerate(words):
    out.append('\t{ 0%03o, 0x%02x, 0x%02x, %2d },\t// %03o %s' % (nxt, ctl, alu, spa, loc, name))
out.append('};')
open(os.path.join(HERE, 'microcode.cpp'), 'w').write('\n'.join(out) + '\n')

out = ['// DEC microstep tags of the KD11-B control store, indexed by microaddress.',
       '// Generated by gen_microcode.py from the transcription of the microcode',
       '// listing in the 11/05 engineering drawings (the tags are the same in the',
       '// 1973 rev E and 1976 rev F sets). 42 of the 256 locations are not in the',
       '// listing; they are empty. The tags are the step names used by the',
       '// microprogram flow diagrams.',
       '#include <avr/pgmspace.h>',
       '#include "microtags.h"', '',
       'const char microTags[256][MICROTAG_LEN + 1] PROGMEM = {']
for a in range(0, 256, 8):
    out.append('\t' + ' '.join('"%s",' % words[i][4] for i in range(a, a + 8)) + '\t// %03o' % a)
out.append('};')
open(os.path.join(HERE, 'microtags.cpp'), 'w').write('\n'.join(out) + '\n')
